In [1]:
from lorentz import Lorentz
import torch

In [2]:
man = Lorentz(k=1.0)
xs = torch.randn(2, 3, 4, 5)  # Example tensor of shape (2, 3, 4, 5)
time = torch.sqrt(1 + torch.sum(xs ** 2, dim=-1, keepdim=True))  # Shape (2, 3, 4, 1)
xs = torch.cat([time, xs], dim=-1)  # Shape (2, 3, 4, 6)

In [3]:
man.lorentz_midpoint(xs)

tensor([[[ 1.0610e+00, -1.5297e-01,  5.2889e-02, -2.2810e-01, -9.7824e-02,
           1.9483e-01],
         [ 1.1219e+00, -3.3158e-01,  1.8577e-03, -3.4856e-01,  7.8278e-02,
           1.4530e-01],
         [ 1.0408e+00, -1.5848e-01,  1.4276e-01,  1.1343e-01, -1.5192e-01,
          -4.2925e-02]],

        [[ 1.0995e+00, -3.1977e-01, -8.5046e-02, -1.8268e-01, -2.5579e-01,
          -2.5858e-02],
         [ 1.0833e+00,  2.2967e-01,  5.5281e-03,  1.7880e-01,  1.0804e-01,
           2.7776e-01],
         [ 1.1509e+00,  9.2943e-02,  4.7927e-01, -1.0052e-03, -2.8447e-01,
           7.2750e-02]]])

In [4]:
xs

tensor([[[[ 2.4557, -0.0603,  0.5350,  0.1547,  2.1044,  0.5367],
          [ 3.0213,  0.3163,  0.6245, -2.4158, -0.9759,  0.9219],
          [ 3.3287, -1.6411, -0.5583, -0.3150, -2.2426, -1.3954],
          [ 2.2239, -0.2050, -0.0515,  0.2048,  0.0972,  1.9621]],

         [[ 2.0548, -0.9389, -0.1300, -0.7860, -0.7422,  1.0747],
          [ 1.8251,  0.1042,  0.7320, -1.2829,  0.2313,  0.2919],
          [ 2.0505, -1.5739, -0.3628, -0.4543,  0.6097,  0.1339],
          [ 1.2983,  0.2721, -0.2272,  0.2773,  0.4056, -0.5643]],

         [[ 3.8168, -0.6844,  2.8828,  1.9074,  0.0831, -1.0697],
          [ 2.5988, -1.6614, -0.4911, -0.2778, -1.3128,  0.9757],
          [ 1.7533,  1.0128, -0.9357,  0.2869,  0.2076,  0.2179],
          [ 1.4851, -0.1371, -0.1319, -0.8644, -0.3871, -0.5220]]],


        [[[ 2.1574, -0.5839, -1.4406, -0.1730, -1.0005,  0.4555],
          [ 1.5199, -0.4932, -0.4099,  0.2652,  0.8890,  0.1951],
          [ 2.5113, -0.1571,  0.4878, -1.0358, -1.1373, -1.6364],
  

In [5]:
man.distL(xs, xs)

tensor([[[ 9.5367e-07, -1.9073e-06,  0.0000e+00,  4.7684e-07],
         [ 4.7684e-07, -4.7684e-07,  9.5367e-07,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  4.7684e-07,  2.3842e-07]],

        [[ 0.0000e+00,  0.0000e+00, -9.5367e-07, -4.7684e-07],
         [ 9.5367e-07, -4.7684e-07,  0.0000e+00,  4.7684e-07],
         [ 0.0000e+00,  0.0000e+00, -1.9073e-06, -9.5367e-07]]])

In [6]:
man.dist(xs, xs)

tensor([[[[9.7656e-04, 2.8914e+00, 3.3231e+00, 2.1106e+00],
          [2.8914e+00, 4.8828e-04, 2.9161e+00, 2.4073e+00],
          [3.3231e+00, 2.9161e+00, 4.8828e-04, 2.9990e+00],
          [2.1106e+00, 2.4073e+00, 2.9990e+00, 6.9053e-04]],

         [[6.9053e-04, 1.6865e+00, 1.6260e+00, 2.0684e+00],
          [1.6865e+00, 4.8828e-04, 1.8974e+00, 1.7392e+00],
          [1.6260e+00, 1.8974e+00, 9.7656e-04, 1.7493e+00],
          [2.0684e+00, 1.7392e+00, 1.7493e+00, 4.8828e-04]],

         [[4.8828e-04, 3.1663e+00, 2.9679e+00, 2.6450e+00],
          [3.1663e+00, 4.8828e-04, 2.4642e+00, 1.8722e+00],
          [2.9679e+00, 2.4642e+00, 6.9053e-04, 1.7842e+00],
          [2.6450e+00, 1.8722e+00, 1.7842e+00, 4.8828e-04]]],


        [[[4.8828e-04, 1.8463e+00, 2.3816e+00, 1.9683e+00],
          [1.8463e+00, 4.8828e-04, 2.3977e+00, 1.8806e+00],
          [2.3816e+00, 2.3977e+00, 4.8828e-04, 2.2206e+00],
          [1.9683e+00, 1.8806e+00, 2.2206e+00, 4.8828e-04]],

         [[9.7656e-04, 1.9929e